# Generated by Django 2.2.8 on 2020-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200114_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'card'), ('Cash On Delivery', 'cash on delivery')], default='cash on delivery', max_length=50),
        ),
    ]
