# Generated by Django 2.2.8 on 2020-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200116_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Card', 'Card'), ('COD', 'COD')], max_length=50, null=True),
        ),
    ]
