# Generated by Django 2.2.9 on 2020-01-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200116_2116'),
        ('orders', '0005_auto_20200116_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BillingProfile'),
        ),
    ]
