# Generated by Django 2.2.9 on 2020-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Shipped', 'Shipped'), ('Paid', 'Paid')], default='created', max_length=50),
        ),
    ]
