# Generated by Django 2.2.9 on 2020-01-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Shipped', 'Shipped'), ('Paid', 'Paid')], default='Created', max_length=50),
        ),
    ]
