# Generated by Django 2.2.9 on 2020-01-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200119_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Credit card', 'Credit card'), ('Debit card', 'Debit card'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=50),
        ),
    ]
