# Generated by Django 2.2.9 on 2020-04-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated']},
        ),
    ]
