# Generated by Django 2.2.6 on 2019-12-18 05:23

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=39)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_file_path)),
            ],
        ),
    ]
