# Generated by Django 2.2.8 on 2020-01-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'mobiles'), ('Accessories', 'accessories'), ('Watches', 'watches'), ('Shirts', 'shirts'), ('Shoes', 'shoes'), ('Others', 'others')], max_length=120),
        ),
    ]
